{"name": "Авторизация с невалидными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_RESET at https://zimaev.github.io/pom/\nCall log:\n  - navigating to \"https://zimaev.github.io/pom/\", waiting until \"load\"", "trace": "login_page = <pages.login_page.LoginPage object at 0x7534a8e0d070>\n\n    @allure.epic('Эпик задачи')\n    @allure.story('Авторизация')\n    @allure.title('Авторизация с невалидными данными')\n    @allure.description('Тест входа с невалидными данными')\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_failure(login_page):\n        with allure.step('Открыть страницу авторизации'):\n>           login_page.navigate()\n\ntest_login.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../pages/login_page.py:17: in navigate\n    self.page.goto(settings.LOGIN_URL)\n../playwright_project_2_env/lib/python3.12/site-packages/playwright/sync_api/_generated.py:9024: in goto\n    self._sync(\n../playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n../playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n../playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x7534a91a3650>, cb = <function Channel.send.<locals>.<lambda> at 0x7534a8db7740>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_RESET at https://zimaev.github.io/pom/\nE           Call log:\nE             - navigating to \"https://zimaev.github.io/pom/\", waiting until \"load\"\n\n../playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_connection.py:528: Error"}, "description": "Тест входа с невалидными данными", "steps": [{"name": "Открыть страницу авторизации", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_RESET at https://zimaev.github.io/pom/\nCall log:\n  - navigating to \"https://zimaev.github.io/pom/\", waiting until \"load\"\n\n", "trace": "  File \"/home/hama/Документы/PythonTests/playwright_project_2/tests/test_login.py\", line 12, in test_login_failure\n    login_page.navigate()\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/pages/login_page.py\", line 17, in navigate\n    self.page.goto(settings.LOGIN_URL)\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/sync_api/_generated.py\", line 9024, in goto\n    self._sync(\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/hama/Документы/PythonTests/playwright_project_2/playwright_project_2_env/lib/python3.12/site-packages/playwright/_impl/_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1747806838117, "stop": 1747806838624}], "attachments": [{"name": "log", "source": "dcaea3e5-53a4-4f44-8459-15637a3a15d9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "dce673e7-1956-44ca-849a-c76e59969165-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1747806838117, "stop": 1747806838626, "uuid": "41c4a344-6cac-4414-89e1-3296f338454c", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "story", "value": "Авторизация"}, {"name": "epic", "value": "Эпик задачи"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "hama-ZenBook-UX425IA-UM425IA"}, {"name": "thread", "value": "70090-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}